### PR TITLE
Temporary fix for broken Result release.

### PR DESCRIPTION
**Pull request by jnutting**
Xcode 7.1 made Result a little broken. Rob has fixed that, but
not yet put out a release, so I'm pointing at a specific commit
(just so we can have something that works) for now.

### CODE REVIEW

**Comment by gfontenot** [comment]
Is there a better branch or something that we can/should point at instead of a specific SHA? `master` maybe?

**Comment by jnutting** [comment]
Not sure. I just did the simplest thing I could, as a temporary fix. Maybe master would be better.

**Comment by gfontenot** [comment]
They also just released a new beta, if we want to point to that.

**Comment by paulyoung** [comment]
I'm currently facing this issue with Carthage when trying to use Swish with ReactiveCocoa `v4.0.0-alpha.3`

```
Could not pick a version for github "antitypical/Result", due to mutually incompatible requirements:
    "0.6.0-beta.5"
    "0.6.0-beta.3"
```

Would love to see a version of Swish that points to Result `0.6.0-beta.5` for that reason.

**Comment by paulyoung** [comment]
Anything I can do to help move this along?

**Pull request closed without merging**
